// This is an example config file. 
// Do NOT edit this file.
// Instead, put your GEMINI_API_KEY in the .env file in the root directory
// and run `python build.py` to generate the real config.js
const GEMINI_API_KEY = "YOUR_API_KEY_HERE";
